import turtle
tartaruga=turtle.Turtle()
tartaruga.hideturtle()
campo=turtle.Screen()
tartaruga.pensize(3)
lados=int(input('Introduza o número de lados do polígono: '))
comprimento=int(input('Introduza o comprimento dos lados do polígono: '))
cor_borda=input('Introduza a cor das bordas do polígono: ')
cor_interior=input('Introduza a cor do interior do polígono: ')
campo=turtle.Screen()
angulo_inicial=float((180*(lados-2)/lados))
angulo_final=float(180-angulo_inicial)
tartaruga.color(cor_interior)
tartaruga.pencolor(cor_borda)
tartaruga.begin_fill()
for i in range(lados):
    tartaruga.forward(comprimento)
    tartaruga.left(angulo_final)
tartaruga.end_fill()
campo.exitonclick()