import turtle
campo=turtle.Screen()
tartaruga=turtle.Turtle()
tartaruga.hideturtle()
tartaruga.pensize(3)
tartaruga.penup()
tartaruga.setpos(-150,150)
tartaruga.left(90)
tartaruga.pendown()
for i in range(4):
    tartaruga.forward(150)
    tartaruga.left(90)
tartaruga.penup()
tartaruga.home()
tartaruga.setpos(150,150)
tartaruga.pendown()
for i in range(3):
    tartaruga.forward(175)
    tartaruga.left(120)
tartaruga.penup()
tartaruga.home()
tartaruga.setpos(-190,-150)
tartaruga.left(180)
tartaruga.pendown()
for i in range(6):
    tartaruga.forward(100)
    tartaruga.left(60)
tartaruga.penup()
tartaruga.home()
tartaruga.setpos(190,-150)
tartaruga.pendown()
for i in range(8):
    tartaruga.forward(75)
    tartaruga.right(45)
campo.exitonclick()